### PR TITLE
final

### PR DESCRIPTION
**Pull request by kaavyabaranwal**
minor changes in tags

### CODE REVIEW

**Comment by earthtoyash** [comment]
There are some things, like the 
The Tryhackme badge is not loading completely where it is placed now. 
The buttons of social media, can you please add icons to them.
And the last thing, when you view this site on android, let's just say that it is not ideal. 

I would really appreciate if you could make the following change.

**Comment by kaavyabaranwal** [comment]
Okay, I'll look into these changes for sure, but do expect a delay of a few
days as I am also working on some other projects right now!
Thank you for your co-operation :)

**Comment by kaavyabaranwal** [comment]
Also, is there someone else making changes on this website simultaneously?
Because I never positioned the try hack me badge there and I am seeing
lines of code i never wrote 🤔

**Comment by earthtoyash** [comment]
What is your handle on LinkedIn??

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by earthtoyash** [comment]
Yes, it is an opensource project so ofcourse other people are working on it. BUt yours pull request was the best, Now please tell me your linked handle so I can give the shoutout, is it this [linkedin.com/in/kaavya-baranwal](https://www.linkedin.com/in/kaavya-baranwal) ??

**Comment by earthtoyash** [comment]
and one more thing, I just found out this, it would be really helpful if you could do something about that.
(https://user-images.githubusercontent.com/112372825/193434881-2fa5c6b3-14f6-4b96-a9ec-1093585d8ae3.jpg)

**Comment by kaavyabaranwal** [comment]
Yes , this is the one

**Comment by earthtoyash** [comment]
Okay, I'll get back to it!

Sent from Proton Mail mobile

-------- Original Message --------

**Pull request merged**
