### PR TITLE
refactor(SocialLinks): harmonize css / layout

### PR DESCRIPTION
**Pull request by exrol**

### CODE REVIEW

**Comment by exrol** [comment]
Redesign of your social links cards/buttons

**Comment by earthtoyash** [comment]
can you please change the Tryhackme logo, it is wrong. [https://assets.tryhackme.com/img/logo/tryhackme_logo_full.svg](This is the link to the correct logo)

**Comment by exrol** [comment]
:+1:

**Comment by earthtoyash** [comment]
Final request: 
Remove the rows and change the logo of tryhackme, and the PR will me merged. 
Can you please do that ?

**Pull request closed without merging**
